/* Shared application logic extracted from original index.html */
const DB = {
  students:[
    {student_number:241189694,name:'Gidi WC',student_email:'241189694@tut4life.ac.za'},
    {student_number:241326810,name:'Sekosana KM',student_email:'241326810@tut4life.ac.za'},
    {student_number:241010082,name:'Ngobeni KH',student_email:'241010082@tut4life.ac.za'},
    {student_number:241381935,name:'Makuya AJ',student_email:'241381935@tut4life.ac.za'},
    {student_number:241747476,name:'Manthata SH',student_email:'241747476@tut4life.ac.za'}
  ],
  labs:[
    {lab_id:1,name:'I-Center 1',lab_name:'I-Center Computer Lab 1',total_pc:70},
    {lab_id:2,name:'I-Center 2',lab_name:'I-Center Computer Lab 2',total_pc:70},
    {lab_id:3,name:'CS Lab',lab_name:'Computer Science Laboratory',total_pc:40}
  ],
  pcs:[
    {pc_id:1,lab_id:1,status:'available'},{pc_id:2,lab_id:1,status:'in_use'},{pc_id:3,lab_id:2,status:'available'},
    {pc_id:4,lab_id:2,status:'broken'},{pc_id:5,lab_id:3,status:'available'}
  ],
  bookings:[
    {booking_id:1,student_number:241189694,pc_id:1,start_time:'2026-04-01T08:00',end_time:'2026-04-01T09:00',booking_status:'completed'},
    {booking_id:2,student_number:241326810,pc_id:2,start_time:'2026-04-01T09:00',end_time:'2026-04-01T11:00',booking_status:'active'},
    {booking_id:3,student_number:241010082,pc_id:3,start_time:'2026-04-01T10:00',end_time:'2026-04-01T12:00',booking_status:'pending'},
    {booking_id:4,student_number:241381935,pc_id:4,start_time:'2026-04-01T11:00',end_time:'2026-04-01T13:00',booking_status:'cancelled'},
    {booking_id:5,student_number:241747476,pc_id:5,start_time:'2026-04-02T08:00',end_time:'2026-04-02T10:00',booking_status:'confirmed'}
  ],
  sessions:[
    {session_id:1,booking_id:1,student_number:241189694,pc_id:1,check_in_time:'2026-04-01T08:02',end_time:'2026-04-01T08:55'},
    {session_id:2,booking_id:2,student_number:241326810,pc_id:2,check_in_time:'2026-04-01T09:01',end_time:null},
    {session_id:3,booking_id:3,student_number:241010082,pc_id:3,check_in_time:'2026-04-01T10:03',end_time:'2026-04-01T11:58'},
    {session_id:4,booking_id:4,student_number:241381935,pc_id:4,check_in_time:'2026-04-01T11:00',end_time:'2026-04-01T12:45'},
    {session_id:5,booking_id:5,student_number:241747476,pc_id:5,check_in_time:'2026-04-02T08:05',end_time:'2026-04-02T09:50'}
  ],
  maintenance:[
    {maintenance_id:1,pc_id:4,status:'in_progress'},{maintenance_id:2,pc_id:2,status:'resolved'},
    {maintenance_id:3,pc_id:3,status:'reported'},{maintenance_id:4,pc_id:1,status:'resolved'},
    {maintenance_id:5,pc_id:5,status:'in_progress'}
  ],
  notifications:[
    {notification_id:1,student_number:241189694,message:'Your booking for PC 1 on 01 Apr at 08:00 is confirmed.',type:'booking',sent_time:'2026-04-01T07:50'},
    {notification_id:2,student_number:241326810,message:'A PC is now available in Lab 1. Check in within 5 minutes.',type:'session',sent_time:'2026-04-01T08:55'},
    {notification_id:3,student_number:241010082,message:'You have 30 minutes remaining in your current session.',type:'session',sent_time:'2026-04-01T11:30'},
    {notification_id:4,student_number:241381935,message:'Your extension request of 15 minutes has been approved.',type:'booking',sent_time:'2026-04-01T12:00'},
    {notification_id:5,student_number:241747476,message:'Your booking was marked as no show and has been cancelled.',type:'booking',sent_time:'2026-04-02T08:06'}
  ],
  extensions:[
    {extension_id:1,booking_id:1,minutes_requested:15,status:'approved',approval_time:'2026-04-01T08:05'},
    {extension_id:2,booking_id:2,minutes_requested:10,status:'pending',approval_time:null},
    {extension_id:3,booking_id:3,minutes_requested:20,status:'declined',approval_time:'2026-04-01T10:30'},
    {extension_id:4,booking_id:4,minutes_requested:10,status:'pending',approval_time:null},
    {extension_id:5,booking_id:5,minutes_requested:15,status:'approved',approval_time:'2026-04-02T08:10'}
  ],
  waitlist:[
    {waitlist_id:1,student_number:241189694,lab_id:1,status:'waiting'},{waitlist_id:2,student_number:241326810,lab_id:2,status:'notified'},
    {waitlist_id:3,student_number:241010082,lab_id:1,status:'expired'},{waitlist_id:4,student_number:241381935,lab_id:3,status:'waiting'},
    {waitlist_id:5,student_number:241747476,lab_id:2,status:'waiting'}
  ]
};
const IDs={lab:10,pc:10,session:10,maint:10,notif:10,ext:10,booking:10,wl:10,student:10};
const gS=n=>DB.students.find(s=>s.student_number===n);
const gP=id=>DB.pcs.find(p=>p.pc_id===id);
const gL=id=>DB.labs.find(l=>l.lab_id===id);
const gB=id=>DB.bookings.find(b=>b.booking_id===id);
const fmt=t=>t?t.replace('T',' '):'—';
const now=()=>{const d=new Date();return new Date(d-d.getTimezoneOffset()*6e4).toISOString().slice(0,16);} 
const labOpts=()=>DB.labs.map(l=>`<option value="${l.lab_id}">${l.name}</option>`).join('');
const stuOpts=()=>DB.students.map(s=>`<option value="${s.student_number}">${s.student_number} — ${s.name}</option>`).join('');
const bkOpts=()=>DB.bookings.map(b=>`<option value="${b.booking_id}">#${b.booking_id} — ${b.student_number}</option>`).join('');
function sb(s){const m={available:'bg',operational:'bg',resolved:'bg',confirmed:'bb',pending:'ba',in_use:'ba',in_progress:'ba',maintenance:'ba',reported:'ba',broken:'br',closed:'br',cancelled:'br',no_show:'br',inactive:'bgr',completed:'bgr',approved:'bg',declined:'br',active:'bb',waiting:'ba',notified:'bb',expired:'bgr',booking:'bb',session:'bg',general:'bgr'}; return`<span class="badge ${m[s]||'bgr'}">${String(s).replace(/_/g,' ')}</span>`;}
function renderDash(){const el=document.getElementById('d-s'); if(!el) return; const avail=DB.pcs.filter(p=>p.status==='available').length;const pct=Math.round(avail/DB.pcs.length*100);document.getElementById('d-s').textContent=DB.students.length;document.getElementById('d-ss').textContent=DB.students.length+' registered';document.getElementById('d-l').textContent=DB.labs.length;document.getElementById('d-pc').textContent=DB.pcs.length;document.getElementById('d-pcs').textContent=avail+' available';document.getElementById('d-b').textContent=DB.bookings.length;document.getElementById('d-bs').textContent=DB.bookings.filter(b=>b.booking_status==='active').length+' active';const ase=DB.sessions.filter(s=>!s.end_time).length;document.getElementById('d-se').textContent=DB.sessions.length;document.getElementById('d-ses').textContent=ase+' active';document.getElementById('d-m').textContent=DB.maintenance.length;document.getElementById('d-ms').textContent=DB.maintenance.filter(m=>m.status==='in_progress').length+' in progress';document.getElementById('avail-pct').textContent=pct+'%';const bar=document.getElementById('avail-bar'); if(bar) {bar.style.width=pct+'%';bar.style.background=pct>60?'var(--success)':pct>30?'var(--warn)':'var(--red)';} const lab=document.getElementById('avail-label'); if(lab){const inuse=DB.pcs.filter(p=>p.status==='in_use').length;const brok=DB.pcs.filter(p=>p.status==='broken').length;lab.textContent=`${avail} available · ${inuse} in use · ${brok} broken`;} }
function renderStudents(data){const tb=document.getElementById('s-tb'); if(!tb) return; tb.innerHTML=data.length?data.map(s=>`<tr><td><strong>${s.student_number}</strong></td><td>${s.name}</td><td>${s.student_email}</td><td><div class="action-group"><button class="btn btn-blue btn-sm" onclick="openEditStudent(${s.student_number})"><i class="fa fa-edit"></i> Edit</button><button class="btn btn-red btn-sm" onclick="confirmDel('student',${s.student_number},'${s.name}')"><i class="fa fa-trash"></i> Delete</button></div></td></tr>`).join(''):'<tr><td colspan="4" class="tbl-empty">No students found.</td></tr>';} 
function addStudent(){const elNum=document.getElementById('as-num');const elName=document.getElementById('as-name');const elEmail=document.getElementById('as-email'); if(!elNum||!elName||!elEmail){toast('Please fill required fields','er');return;}const num=parseInt(elNum.value);const name=elName.value.trim();const email=elEmail.value.trim();if(!num||!name||!email){toast('Please fill in all required fields.','er');return;}if(DB.students.find(s=>s.student_number===num)){toast('Student number already exists.','er');return;}DB.students.push({student_number:num,name,student_email:email});closeModal('m-add-student');elNum.value='';elName.value='';elEmail.value='';renderStudents(DB.students);updateBadges();toast('Student added successfully.');}
function openEditStudent(num){const s=gS(num);if(!s)return;const elN=document.getElementById('es-n');const elNd=document.getElementById('es-nd');const elName=document.getElementById('es-name');const elEmail=document.getElementById('es-email'); if(!elN||!elNd||!elName||!elEmail) return;elN.value=s.student_number;elNd.value=s.student_number;elName.value=s.name;elEmail.value=s.student_email;openModal('m-student');}
function saveStudent(){const num=parseInt(document.getElementById('es-n').value);const s=gS(num);if(!s)return;const name=document.getElementById('es-name').value.trim();const email=document.getElementById('es-email').value.trim();if(!name||!email){toast('Please fill in all required fields.','er');return;}s.name=name;s.student_email=email;closeModal('m-student');renderStudents(DB.students);toast('Student updated successfully.');}
function renderLabs(data){const tb=document.getElementById('l-tb'); if(!tb) return; tb.innerHTML=data.length?data.map(l=>`<tr><td><strong>#${l.lab_id}</strong></td><td>${l.name}</td><td>${l.lab_name}</td><td>${l.total_pc}</td><td><div class="action-group"><button class="btn btn-blue btn-sm" onclick="openEditLab(${l.lab_id})"><i class="fa fa-edit"></i> Edit</button><button class="btn btn-red btn-sm" onclick="confirmDel('lab',${l.lab_id},'${l.name}')"><i class="fa fa-trash"></i> Delete</button></div></td></tr>`).join(''):'<tr><td colspan="5" class="tbl-empty">No labs found.</td></tr>';} 
function createLab(){const name=document.getElementById('cl-n').value.trim();const fn=document.getElementById('cl-fn').value.trim();const pcs=parseInt(document.getElementById('cl-p').value)||30;if(!name||!fn){toast('Please fill in all required fields.','er');return;}DB.labs.push({lab_id:IDs.lab++,name,lab_name:fn,total_pc:pcs});closeModal('m-lab');document.getElementById('cl-n').value='';document.getElementById('cl-fn').value='';document.getElementById('cl-p').value='30';renderLabs(DB.labs);updateBadges();toast('Laboratory created successfully.');}
function openEditLab(id){const l=gL(id);if(!l)return;document.getElementById('el-id').value=l.lab_id;document.getElementById('el-idd').value='#'+l.lab_id;document.getElementById('el-n').value=l.name;document.getElementById('el-fn').value=l.lab_name;document.getElementById('el-p').value=l.total_pc;openModal('m-editlab');}
function saveLab(){const id=parseInt(document.getElementById('el-id').value);const l=gL(id);if(!l)return;const name=document.getElementById('el-n').value.trim();const fn=document.getElementById('el-fn').value.trim();const pcs=parseInt(document.getElementById('el-p').value)||30;if(!name||!fn){toast('Please fill in all required fields.','er');return;}l.name=name;l.lab_name=fn;l.total_pc=pcs;closeModal('m-editlab');renderLabs(DB.labs);toast('Laboratory updated successfully.');}
function renderPCs(data){const tb=document.getElementById('pc-tb'); if(!tb) return; const statusIco={available:'<i class="fa fa-circle" style="color:#16a34a"></i>',in_use:'<i class="fa fa-circle" style="color:#f59e0b"></i>',broken:'<i class="fa fa-circle" style="color:#ef4444"></i>',reserved:'<i class="fa fa-circle" style="color:#3b82f6"></i>'}; tb.innerHTML=data.length?data.map(p=>{const lab=gL(p.lab_id);return`<tr><td><strong>${p.pc_id}</strong></td><td>${lab?lab.name:'—'}</td><td>${(statusIco[p.status]||'⚪')} ${sb(p.status)}</td><td><div class="action-group"><button class="btn btn-blue btn-sm" onclick="openEditPC(${p.pc_id})"><i class="fa fa-edit"></i> Edit</button><button class="btn btn-red btn-sm" onclick="confirmDel('pc',${p.pc_id},'PC ${p.pc_id}')"><i class="fa fa-trash"></i> Delete</button></div></td></tr>`;}).join(''):'<tr><td colspan="4" class="tbl-empty">No computers found.</td></tr>'; const grid=document.getElementById('pc-grid-inner'); if(grid) grid.innerHTML=data.map(p=>{const lab=gL(p.lab_id);const ico=p.status==='available'?'<i class="fa fa-desktop" style="color:#16a34a"></i>':p.status==='in_use'?'<i class="fa fa-bolt" style="color:#f59e0b"></i>':p.status==='broken'?'<i class="fa fa-times-circle" style="color:#ef4444"></i>':'<i class="fa fa-question-circle"></i>';return`<div class="pc-tile"><div class="pc-tile-ico">${ico}</div><div class="pc-tile-name">PC ${p.pc_id}</div><div class="pc-tile-st">${lab?lab.name:'—'}</div><div style="margin-top:8px;">${sb(p.status)}</div><div style="display:flex;gap:4px;margin-top:8px;"><button class="btn btn-blue btn-xs" style="flex:1;" onclick="openEditPC(${p.pc_id})"><i class="fa fa-edit"></i></button><button class="btn btn-red btn-xs" style="flex:1;" onclick="confirmDel('pc',${p.pc_id},'PC ${p.pc_id}')"><i class="fa fa-trash"></i></button></div></div>`;}).join(''); }
function openAddPC(){const el=document.getElementById('ap-lab'); if(!el) return; el.innerHTML='<option value="">— Select Lab —</option>'+labOpts();openModal('m-add-pc');}
function addPC(){const labId=parseInt(document.getElementById('ap-lab').value);const status=document.querySelector('[name="ap-s"]:checked').value;if(!labId){toast('Please select a lab.','er');return;}DB.pcs.push({pc_id:IDs.pc++,lab_id:labId,status});closeModal('m-add-pc');renderPCs(DB.pcs);updateBadges();toast('Computer added successfully.');}
function openEditPC(id){const p=gP(id);if(!p)return;const elId=document.getElementById('ep-id');if(!elId) return;document.getElementById('ep-id').value=p.pc_id;document.getElementById('ep-idd').value='PC '+p.pc_id;document.getElementById('ep-lab').innerHTML=labOpts();document.getElementById('ep-lab').value=p.lab_id;document.querySelectorAll('[name="ep-s"]').forEach(r=>r.checked=(r.value===p.status));updateEditPCImgByStatus(p.status);openModal('m-edit-pc');}
function updateEditPCImg(radio){updateEditPCImgByStatus(radio.value);} 
function updateEditPCImgByStatus(status){const box=document.getElementById('ep-img-box');const img=document.getElementById('ep-img');const lbl=document.getElementById('ep-img-lbl'); if(!box||!img||!lbl) return;const map={available:{c:'avail',i:'<i class="fa fa-desktop" style="font-size:36px;color:#16a34a"></i>',t:'This computer is AVAILABLE'},in_use:{c:'inuse',i:'<i class="fa fa-bolt" style="font-size:36px;color:#f59e0b"></i>',t:'This computer is currently IN USE'},broken:{c:'broken',i:'<i class="fa fa-times-circle" style="font-size:36px;color:#ef4444"></i>',t:'This computer is BROKEN — needs maintenance'},reserved:{c:'reserved',i:'<i class="fa fa-lock" style="font-size:36px;color:#3b82f6"></i>',t:'This computer is RESERVED'}};const s=map[status]||{c:'',i:'<i class="fa fa-desktop" style="font-size:36px"></i>',t:'Unknown status'};box.className='pc-img-box '+s.c;img.innerHTML=s.i;lbl.textContent=s.t;}
function savePC(){const id=parseInt(document.getElementById('ep-id').value);const p=gP(id);if(!p)return;const status=document.querySelector('[name="ep-s"]:checked').value;const labId=parseInt(document.getElementById('ep-lab').value);if(!labId){toast('Please select a lab.','er');return;}p.status=status;p.lab_id=labId;closeModal('m-edit-pc');renderPCs(DB.pcs);toast('Computer updated successfully.');}
function renderBookings(data){const tb=document.getElementById('b-tb'); if(!tb) return; tb.innerHTML=data.length?data.map(b=>{const st=gS(b.student_number);return`<tr><td><strong>#${b.booking_id}</strong></td><td>${st?st.name:b.student_number}</td><td>PC-${b.pc_id}</td><td>${fmt(b.start_time)}</td><td>${fmt(b.end_time)}</td><td>${sb(b.booking_status)}</td><td><div class="action-group"><button class="btn btn-blue btn-sm" onclick="openEditBooking(${b.booking_id})"><i class="fa fa-edit"></i> Edit</button><button class="btn btn-red btn-sm" onclick="confirmDel('booking',${b.booking_id},'Booking #${b.booking_id}')"><i class="fa fa-trash"></i> Delete</button></div></td></tr>`;}).join(''):'<tr><td colspan="7" class="tbl-empty">No bookings found.</td></tr>';} 
function openAddBooking(){const abSt=document.getElementById('ab-stu');const abPc=document.getElementById('ab-pc');if(abSt) abSt.innerHTML='<option value="">— Select Student —</option>'+stuOpts(); if(abPc) abPc.innerHTML='<option value="">— Select Computer —</option>'+DB.pcs.map(p=>`<option value="${p.pc_id}">PC ${p.pc_id} — ${p.status}</option>`).join('');if(document.getElementById('ab-s')) document.getElementById('ab-s').value=now();document.getElementById('ab-e').value='';document.querySelector('[name="ab-st"][value="confirmed"]').checked=true;openModal('m-add-booking');}
function addBooking(){const stNum=parseInt(document.getElementById('ab-stu').value);const pcId=parseInt(document.getElementById('ab-pc').value);const start=document.getElementById('ab-s').value;const end=document.getElementById('ab-e').value;const status=document.querySelector('[name="ab-st"]:checked').value;if(!stNum||!pcId||!start||!end){toast('Please fill in all required fields.','er');return;}DB.bookings.push({booking_id:IDs.booking++,student_number:stNum,pc_id:pcId,start_time:start,end_time:end,booking_status:status});closeModal('m-add-booking');renderBookings(DB.bookings);updateBadges();toast('Booking created successfully.');}
function openEditBooking(id){const b=gB(id);if(!b)return;document.getElementById('ub-id').value=id;document.getElementById('ub-idd').value='Booking #'+id;const st=gS(b.student_number);document.getElementById('ub-st').value=st?st.name:b.student_number;document.getElementById('ub-pc').value='PC-'+b.pc_id;document.getElementById('ub-s').value=b.start_time||'';document.getElementById('ub-e').value=b.end_time||'';document.querySelectorAll('[name="ub-st"]').forEach(r=>r.checked=(r.value===b.booking_status));openModal('m-booking');}
function saveBooking(){const id=parseInt(document.getElementById('ub-id').value);const b=gB(id);const sel=document.querySelector('[name="ub-st"]:checked');if(!b||!sel){toast('Please select a booking status.','er');return;}b.booking_status=sel.value;closeModal('m-booking');renderBookings(DB.bookings);toast('Booking updated successfully.');}
function renderSessions(data){const tb=document.getElementById('se-tb'); if(!tb) return; tb.innerHTML=data.length?data.map(s=>{const st=gS(s.student_number),active=!s.end_time;return`<tr><td><strong>${s.session_id}</strong></td><td>${s.student_number}</td><td>${st?st.name:'—'}</td><td>${s.pc_id}</td><td>${fmt(s.check_in_time)}</td><td>${s.end_time?fmt(s.end_time):'<em style="color:var(--success);font-weight:700;">Active</em>'}</td><td>${active?sb('active'):sb('completed')}</td><td><div class="action-group"><button class="btn btn-blue btn-sm" onclick="openEditSession(${s.session_id})"><i class="fa fa-edit"></i> Edit</button><button class="btn btn-red btn-sm" onclick="confirmDel('session',${s.session_id},'Session #${s.session_id}')"><i class="fa fa-trash"></i> Delete</button></div></td></tr>`;}).join(''):'<tr><td colspan="8" class="tbl-empty">No sessions found.</td></tr>';} 
function openStartSession(){const ssStu=document.getElementById('ss-stu');const ssPc=document.getElementById('ss-pc');const ssBk=document.getElementById('ss-bk');if(ssStu) ssStu.innerHTML='<option value="">— Select Student —</option>'+stuOpts(); if(ssPc) ssPc.innerHTML='<option value="">— Select Available PC —</option>'+DB.pcs.filter(p=>p.status==='available').map(p=>`<option value="${p.pc_id}">PC ${p.pc_id}</option>`).join(''); if(ssBk) ssBk.innerHTML='<option value="">— Select Booking —</option>'+bkOpts(); if(document.getElementById('ss-li')) document.getElementById('ss-li').value=now();if(document.getElementById('ss-lo')) document.getElementById('ss-lo').value='';const box=document.getElementById('pc-img-box'); if(box) {box.className='pc-img-box'; const pi=document.getElementById('pc-img'); if(pi) pi.innerHTML='<i class="fa fa-desktop" style="font-size:40px;color:#9ca3af"></i>'; const pl=document.getElementById('pc-img-lbl'); if(pl) pl.textContent='Select a computer below to see its real-time status';}openModal('m-session');}
function updatePCImg(sel){const val=parseInt(sel.value);const pc=gP(val);const box=document.getElementById('pc-img-box'),img=document.getElementById('pc-img'),lbl=document.getElementById('pc-img-lbl');if(!box||!img||!lbl) return; if(!pc){box.className='pc-img-box';img.textContent='🖥️';lbl.textContent='Select a computer below';return;}const map={available:{c:'avail',i:'<i class="fa fa-desktop" style="font-size:36px;color:#16a34a"></i>',t:`✅ PC ${pc.pc_id} is AVAILABLE — Ready to use`},in_use:{c:'inuse',i:'<i class="fa fa-bolt" style="font-size:36px;color:#f59e0b"></i>',t:`🟡 PC ${pc.pc_id} is IN USE — Currently occupied`},broken:{c:'broken',i:'<i class="fa fa-times-circle" style="font-size:36px;color:#ef4444"></i>',t:`🔴 PC ${pc.pc_id} is BROKEN — Under maintenance`},reserved:{c:'reserved',i:'<i class="fa fa-lock" style="font-size:36px;color:#3b82f6"></i>',t:`🔵 PC ${pc.pc_id} is RESERVED`}};const s=map[pc.status]||{c:'',i:'<i class="fa fa-desktop" style="font-size:36px"></i>',t:'Unknown status'};box.className='pc-img-box '+s.c;img.innerHTML=s.i;lbl.textContent=s.t;}
function startSession(){const sNum=parseInt(document.getElementById('ss-stu').value);const pcId=parseInt(document.getElementById('ss-pc').value);const bkId=parseInt(document.getElementById('ss-bk').value)||null;const checkin=document.getElementById('ss-li').value;const endtime=document.getElementById('ss-lo').value||null;if(!sNum||!pcId||!checkin){toast('Please fill in all required fields.','er');return;}DB.sessions.push({session_id:IDs.session++,booking_id:bkId,student_number:sNum,pc_id:pcId,check_in_time:checkin,end_time:endtime});const pc=gP(pcId);if(pc)pc.status='in_use';closeModal('m-session');renderSessions(DB.sessions);renderPCs(DB.pcs);updateBadges();toast('Session started successfully.');}
function openEditSession(id){const s=DB.sessions.find(x=>x.session_id===id);if(!s)return;const eseId=document.getElementById('ese-id');if(!eseId) return;document.getElementById('ese-id').value=id;document.getElementById('ese-idd').value='Session #'+id;document.getElementById('ese-stu').value=(gS(s.student_number)||{}).name||s.student_number;document.getElementById('ese-ci').value=s.check_in_time||'';document.getElementById('ese-et').value=s.end_time||'';openModal('m-edit-session');}
function saveSession(){const id=parseInt(document.getElementById('ese-id').value);const s=DB.sessions.find(x=>x.session_id===id);if(!s)return;s.check_in_time=document.getElementById('ese-ci').value||s.check_in_time;s.end_time=document.getElementById('ese-et').value||null;closeModal('m-edit-session');renderSessions(DB.sessions);toast('Session updated successfully.');}
function renderMaint(data){const tb=document.getElementById('m-tb'); if(!tb) return; tb.innerHTML=data.length?data.map(m=>{return`<tr><td><strong>${m.maintenance_id}</strong></td><td>${m.pc_id}</td><td>${sb(m.status)}</td><td><div class="action-group"><button class="btn btn-blue btn-sm" onclick="openEditMaint(${m.maintenance_id})"><i class="fa fa-edit"></i> Edit</button><button class="btn btn-red btn-sm" onclick="confirmDel('maint',${m.maintenance_id},'Maintenance #${m.maintenance_id}')"><i class="fa fa-trash"></i> Delete</button></div></td></tr>`;}).join(''):'<tr><td colspan="4" class="tbl-empty">No maintenance reports found.</td></tr>';} 
function openReportMaint(){const el=document.getElementById('rm-pc'); if(!el) return; el.innerHTML='<option value="">— Select Computer —</option>'+DB.pcs.map(p=>`<option value="${p.pc_id}">PC ${p.pc_id} — ${p.status}</option>`).join('');document.querySelector('[name="rm-s"][value="reported"]').checked=true;openModal('m-maint');}
function reportMaint(){const pcId=parseInt(document.getElementById('rm-pc').value);const status=document.querySelector('[name="rm-s"]:checked').value;if(!pcId){toast('Please select a computer.','er');return;}DB.maintenance.push({maintenance_id:IDs.maint++,pc_id:pcId,status});const pc=gP(pcId);if(pc)pc.status='broken';closeModal('m-maint');renderMaint(DB.maintenance);renderPCs(DB.pcs);updateBadges();toast('Maintenance issue reported successfully.');}
function openEditMaint(id){const m=DB.maintenance.find(x=>x.maintenance_id===id);if(!m)return;document.getElementById('em-id').value=id;document.getElementById('em-idd').value='Maint #'+id;document.getElementById('em-pc').value='PC '+m.pc_id;document.querySelectorAll('[name="em-s"]').forEach(r=>r.checked=(r.value===m.status));openModal('m-edit-maint');}
function saveMaint(){const id=parseInt(document.getElementById('em-id').value);const m=DB.maintenance.find(x=>x.maintenance_id===id);if(!m)return;const status=document.querySelector('[name="em-s"]:checked').value;m.status=status;closeModal('m-edit-maint');renderMaint(DB.maintenance);toast('Maintenance record updated successfully.');}
function renderNotifs(data){const tb=document.getElementById('n-tb'); if(!tb) return; tb.innerHTML=data.length?data.map(n=>{const st=gS(n.student_number);return`<tr><td><strong>${n.notification_id}</strong></td><td>${st?st.name:'—'}</td><td style="max-width:240px;font-size:12px;">${n.message}</td><td>${sb(n.type)}</td><td>${fmt(n.sent_time)}</td><td><div class="action-group"><button class="btn btn-blue btn-sm" onclick="openEditNotif(${n.notification_id})"><i class="fa fa-edit"></i> Edit</button><button class="btn btn-red btn-sm" onclick="confirmDel('notif',${n.notification_id},'Notification #${n.notification_id}')"><i class="fa fa-trash"></i> Delete</button></div></td></tr>`;}).join(''):'<tr><td colspan="6" class="tbl-empty">No notifications found.</td></tr>';} 
function sendNotif(){const stNum=parseInt(document.getElementById('sn-st').value);const msg=document.getElementById('sn-msg').value.trim();const type=document.querySelector('[name="sn-t"]:checked').value;if(!stNum||!msg){toast('Please fill in all required fields.','er');return;}DB.notifications.push({notification_id:IDs.notif++,student_number:stNum,message:msg,type,sent_time:now()});closeModal('m-notif');renderNotifs(DB.notifications);updateBadges();toast('Notification sent successfully.');}
function openEditNotif(id){const n=DB.notifications.find(x=>x.notification_id===id);if(!n)return;const st=gS(n.student_number);document.getElementById('en-id').value=id;document.getElementById('en-idd').value='Notif #'+id;document.getElementById('en-stu').value=st?st.name:n.student_number;document.getElementById('en-msg').value=n.message;document.querySelectorAll('[name="en-t"]').forEach(r=>r.checked=(r.value===n.type));openModal('m-edit-notif');}
function saveNotif(){const id=parseInt(document.getElementById('en-id').value);const n=DB.notifications.find(x=>x.notification_id===id);if(!n)return;const msg=document.getElementById('en-msg').value.trim();const type=document.querySelector('[name="en-t"]:checked').value;if(!msg){toast('Message cannot be empty.','er');return;}n.message=msg;n.type=type;closeModal('m-edit-notif');renderNotifs(DB.notifications);toast('Notification updated successfully.');}
function renderExts(data){const tb=document.getElementById('ex-tb'); if(!tb) return; tb.innerHTML=data.length?data.map(e=>{const b=gB(e.booking_id),st=b?gS(b.student_number):null;return`<tr><td><strong>${e.extension_id}</strong></td><td>#${e.booking_id}</td><td>${st?st.name:'—'}</td><td><strong>${e.minutes_requested} min</strong></td><td>${sb(e.status)}</td><td>${e.approval_time?fmt(e.approval_time):'—'}</td><td><div class="action-group"><button class="btn btn-blue btn-sm" onclick="openEditExt(${e.extension_id})"><i class="fa fa-edit"></i> Edit</button><button class="btn btn-red btn-sm" onclick="confirmDel('ext',${e.extension_id},'Extension #${e.extension_id}')"><i class="fa fa-trash"></i> Delete</button></div></div></td></tr>`;}).join(''):'<tr><td colspan="7" class="tbl-empty">No extension requests found.</td></tr>';} 
function openAddExt(){const reBk=document.getElementById('re-bk'); if(reBk) reBk.innerHTML='<option value="">— Select Booking —</option>'+bkOpts();document.querySelector('[name="re-m"][value="10"]').checked=true;document.getElementById('re-as').value='pending';openModal('m-add-ext');}
function addExt(){const bkId=parseInt(document.getElementById('re-bk').value);const mins=parseInt(document.querySelector('[name="re-m"]:checked').value);const status=document.getElementById('re-as').value;if(!bkId){toast('Please select a booking.','er');return;}DB.extensions.push({extension_id:IDs.ext++,booking_id:bkId,minutes_requested:mins,status,approval_time:status==='approved'?now():null});closeModal('m-add-ext');renderExts(DB.extensions);updateBadges();toast('Extension request submitted successfully.');}
function openEditExt(id){const e=DB.extensions.find(x=>x.extension_id===id);if(!e)return;document.getElementById('ee-id').value=id;document.getElementById('ee-idd').value='Ext #'+id;document.getElementById('ee-bk').value='Booking #'+e.booking_id;document.querySelectorAll('[name="ee-m"]').forEach(r=>r.checked=(parseInt(r.value)===e.minutes_requested));document.querySelectorAll('[name="ee-s"]').forEach(r=>r.checked=(r.value===e.status));openModal('m-edit-ext');}
function saveExt(){const id=parseInt(document.getElementById('ee-id').value);const e=DB.extensions.find(x=>x.extension_id===id);if(!e)return;const minsEl=document.querySelector('[name="ee-m"]:checked');const statusEl=document.querySelector('[name="ee-s"]:checked');if(!minsEl||!statusEl){toast('Please select all options.','er');return;}e.minutes_requested=parseInt(minsEl.value);e.status=statusEl.value;if(e.status==='approved')e.approval_time=now();closeModal('m-edit-ext');renderExts(DB.extensions);toast('Extension updated successfully.');}
function renderWaitlist(data){const tb=document.getElementById('wl-tb'); if(!tb) return; tb.innerHTML=data.length?data.map(w=>{const st=gS(w.student_number),lab=gL(w.lab_id);return`<tr><td><strong>${w.waitlist_id}</strong></td><td>${w.student_number}</td><td>${st?st.name:'—'}</td><td>${lab?lab.name:'—'}</td><td>${sb(w.status)}</td><td><div class="action-group"><button class="btn btn-blue btn-sm" onclick="openEditWaitlist(${w.waitlist_id})"><i class="fa fa-edit"></i> Edit</button><button class="btn btn-red btn-sm" onclick="confirmDel('wl',${w.waitlist_id},'Waitlist #${w.waitlist_id}')"><i class="fa fa-trash"></i> Delete</button></div></div></td></tr>`;}).join(''):'<tr><td colspan="6" class="tbl-empty">No waitlist entries found.</td></tr>';} 
function openAddWaitlist(){const wlSt=document.getElementById('wl-st');const wlLb=document.getElementById('wl-lb');if(wlSt) wlSt.innerHTML='<option value="">— Select Student —</option>'+stuOpts(); if(wlLb) wlLb.innerHTML='<option value="">— Select Lab —</option>'+labOpts();document.querySelector('[name="wl-s"][value="waiting"]').checked=true;openModal('m-add-waitlist');}
function addWaitlist(){const stNum=parseInt(document.getElementById('wl-st').value);const labId=parseInt(document.getElementById('wl-lb').value);const status=document.querySelector('[name="wl-s"]:checked').value;if(!stNum||!labId){toast('Please fill in all required fields.','er');return;}DB.waitlist.push({waitlist_id:IDs.wl++,student_number:stNum,lab_id:labId,status});closeModal('m-add-waitlist');renderWaitlist(DB.waitlist);updateBadges();toast('Added to waitlist successfully.');}
function openEditWaitlist(id){const w=DB.waitlist.find(x=>x.waitlist_id===id);if(!w)return;const st=gS(w.student_number);document.getElementById('ew-id').value=id;document.getElementById('ew-idd').value='WL #'+id;document.getElementById('ew-stu').value=st?st.name:w.student_number;document.getElementById('ew-lb').innerHTML=labOpts();document.getElementById('ew-lb').value=w.lab_id;document.querySelectorAll('[name="ew-s"]').forEach(r=>r.checked=(r.value===w.status));openModal('m-edit-waitlist');}
function saveWaitlist(){const id=parseInt(document.getElementById('ew-id').value);const w=DB.waitlist.find(x=>x.waitlist_id===id);if(!w)return;const statusEl=document.querySelector('[name="ew-s"]:checked');const labId=parseInt(document.getElementById('ew-lb').value);if(!statusEl){toast('Please select a status.','er');return;}w.status=statusEl.value;w.lab_id=labId;closeModal('m-edit-waitlist');renderWaitlist(DB.waitlist);toast('Waitlist entry updated successfully.');}
function updateBadges(){const ns=['nb-s','nb-l','nb-pc','nb-b','nb-se','nb-m','nb-n','nb-e','nb-w']; if(document.getElementById('nb-s')) document.getElementById('nb-s').textContent=DB.students.length; if(document.getElementById('nb-l')) document.getElementById('nb-l').textContent=DB.labs.length; if(document.getElementById('nb-pc')) document.getElementById('nb-pc').textContent=DB.pcs.length; if(document.getElementById('nb-b')) document.getElementById('nb-b').textContent=DB.bookings.length; if(document.getElementById('nb-se')) document.getElementById('nb-se').textContent=DB.sessions.length; if(document.getElementById('nb-m')) document.getElementById('nb-m').textContent=DB.maintenance.length; if(document.getElementById('nb-n')) document.getElementById('nb-n').textContent=DB.notifications.length; if(document.getElementById('nb-e')) document.getElementById('nb-e').textContent=DB.extensions.length; if(document.getElementById('nb-w')) document.getElementById('nb-w').textContent=DB.waitlist.length; }
function openModal(id){const el=document.getElementById(id); if(el) el.classList.add('open');}
function closeModal(id){const el=document.getElementById(id); if(el) el.classList.remove('open');}
let _del=null;
function confirmDel(type,id,label){_del={type,id};const ch=document.getElementById('conf-h');const ct=document.getElementById('conf-t');const ok=document.getElementById('conf-ok'); if(ch) ch.textContent=`Remove "${label}"?`; if(ct) ct.textContent=`This will permanently delete this record. This action cannot be undone.`; if(ok){ok.onclick=execDel;} openModal('m-confirm');}
function execDel(){if(!_del)return;const{type,id}=_del;const removes={student:()=>{const i=DB.students.findIndex(s=>s.student_number===id);if(i>-1)DB.students.splice(i,1);renderStudents(DB.students);},pc:()=>{const i=DB.pcs.findIndex(p=>p.pc_id===id);if(i>-1)DB.pcs.splice(i,1);renderPCs(DB.pcs);},maint:()=>{const i=DB.maintenance.findIndex(m=>m.maintenance_id===id);if(i>-1)DB.maintenance.splice(i,1);renderMaint(DB.maintenance);},lab:()=>{const i=DB.labs.findIndex(l=>l.lab_id===id);if(i>-1)DB.labs.splice(i,1);renderLabs(DB.labs);},notif:()=>{const i=DB.notifications.findIndex(n=>n.notification_id===id);if(i>-1)DB.notifications.splice(i,1);renderNotifs(DB.notifications);},ext:()=>{const i=DB.extensions.findIndex(e=>e.extension_id===id);if(i>-1)DB.extensions.splice(i,1);renderExts(DB.extensions);},booking:()=>{const i=DB.bookings.findIndex(b=>b.booking_id===id);if(i>-1)DB.bookings.splice(i,1);renderBookings(DB.bookings);},wl:()=>{const i=DB.waitlist.findIndex(w=>w.waitlist_id===id);if(i>-1)DB.waitlist.splice(i,1);renderWaitlist(DB.waitlist);},session:()=>{const i=DB.sessions.findIndex(s=>s.session_id===id);if(i>-1)DB.sessions.splice(i,1);renderSessions(DB.sessions);}};if(removes[type])removes[type]();closeModal('m-confirm');updateBadges();toast('Record deleted successfully.');_del=null;}
function ft(tbodyId,q){const el=document.getElementById(tbodyId); if(!el) return; el.querySelectorAll('tr').forEach(r=>{r.style.display=r.textContent.toLowerCase().includes(q.toLowerCase())?'':'none';});}
function switchTab(module,view,el){if(!el) return; el.closest('.tabs').querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));el.classList.add('active');if(module==='pc'){const lv=document.getElementById('pc-list-view');const gv=document.getElementById('pc-grid-view'); if(lv) lv.style.display=view==='list'?'':'none'; if(gv) gv.style.display=view==='grid'?'':'none';}}
function toast(msg,type='ok'){const t=document.getElementById('toast'); if(!t) return; const ico=document.getElementById('t-ico'); const m=document.getElementById('t-msg'); if(ico) ico.textContent=type==='er'?'❌':type==='wa'?'⚠️':'✅'; if(m) m.textContent=msg; t.className='toast show '+type; setTimeout(()=>t.className='toast',4500);} 
// Initialize light DOM handlers that are safe if elements are missing
document.addEventListener('DOMContentLoaded',()=>{
  document.querySelectorAll('.ov').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open');}));
  const notifBtn=document.querySelector('[data-open="m-notif"]');
  if(notifBtn){notifBtn.addEventListener('click',()=>{const st=document.getElementById('sn-st'); if(st) st.innerHTML='<option value="">— Select Student —</option>'+stuOpts(); const msg=document.getElementById('sn-msg'); if(msg) msg.value=''; const t=document.querySelector('[name="sn-t"][value="booking"]'); if(t) t.checked=true;});}
});

// Expose small helpers to window for inline onclick attributes
window.navTo = function(pageUrl){ window.location.href=pageUrl; };

// Utility to load HTML fragments into placeholders. Returns a Promise.
window.loadFragment = function(placeholderId, fragmentPath){
  return fetch(fragmentPath).then(r=>{if(!r.ok) throw new Error('Failed to load '+fragmentPath);return r.text();}).then(html=>{const el=document.getElementById(placeholderId); if(!el) return; el.innerHTML=html; initModalBehavior();}).catch(err=>{console.warn(err);});
};

// Auto-load modals fragment if a placeholder exists (safe no-op otherwise)
document.addEventListener('DOMContentLoaded',()=>{
  const p=document.getElementById('modals-placeholder');
  if(p){ window.loadFragment('modals-placeholder','modals.html').then(()=>{ /* modals inserted */ }); }
});

// Attach behaviors to modal overlays and data-open triggers
function initModalBehavior(){
  document.querySelectorAll('.ov').forEach(m=>{
    // avoid duplicate listeners
    if(m.__hasInit) return; m.__hasInit = true;
    m.addEventListener('click',e=>{ if(e.target===m) m.classList.remove('open'); });
  });
  // data-open triggers (buttons that open modals)
  document.querySelectorAll('[data-open]').forEach(btn=>{
    if(btn.__hasInit) return; btn.__hasInit = true;
    btn.addEventListener('click',()=>{ const id=btn.getAttribute('data-open'); if(id) openModal(id); });
  });
}

// Called when student selection changes in the Start Session modal
function updateStudentInfo(sel){
  try{
    const val = sel.value ? parseInt(sel.value) : null;
    const bkSelect = document.getElementById('ss-bk');
    if(!bkSelect) return;
    const bookings = val ? DB.bookings.filter(b=>b.student_number===val) : DB.bookings;
    bkSelect.innerHTML = '<option value="">— Select Booking —</option>' + bookings.map(b=>`<option value="${b.booking_id}">#${b.booking_id} — ${b.student_number}</option>`).join('');
  }catch(e){console.warn(e);}
}

// Backwards-compatible SPA navigation helper. If a page element exists, show/hide pages (SPA).
// Otherwise, fall back to loading a separate HTML page (multi-page mode).
function nav(page){
  try{
    const pid = 'page-'+page;
    const el = document.getElementById(pid);
    if(el){
      document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));
      el.classList.add('active');
      document.querySelectorAll('.nl').forEach(n=>n.classList.remove('active'));
      document.querySelectorAll('.nl').forEach(n=>{const oc=n.getAttribute('onclick')||''; if(oc.includes(`'${page}'`)||oc.includes(`"${page}"`)) n.classList.add('active');});
      // call renderer if present
      if(page==='dashboard' && typeof renderDash==='function') renderDash();
      if(page==='students' && typeof renderStudents==='function') renderStudents(DB.students);
      if(page==='labs' && typeof renderLabs==='function') renderLabs(DB.labs);
      if(page==='pcs' && typeof renderPCs==='function') renderPCs(DB.pcs);
      if(page==='bookings' && typeof renderBookings==='function') renderBookings(DB.bookings);
      if(page==='sessions' && typeof renderSessions==='function') renderSessions(DB.sessions);
      if(page==='maintenance' && typeof renderMaint==='function') renderMaint(DB.maintenance);
      if(page==='notifications' && typeof renderNotifs==='function') renderNotifs(DB.notifications);
      if(page==='extensions' && typeof renderExts==='function') renderExts(DB.extensions);
      if(page==='waitlist' && typeof renderWaitlist==='function') renderWaitlist(DB.waitlist);
      updateBadges();
    } else {
      // fallback to separate page
      window.location.href = page + '.html';
    }
  }catch(e){console.warn('nav error',e);window.location.href = page + '.html';}
}

// end of shared JS
